import type { Metadata } from "next";
import {
  Inter,
  Poppins,
  Montserrat,
  Space_Grotesk,
  Italiana,
  Roboto,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigations/navbar";
import Footer from "@/components/navigations/footer";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const italiana = Italiana({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Pixel Joy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-foreground text-background ${poppins.className}`}>
        <>
          <Navbar />
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
