import type { Metadata } from "next";

import { Poppins } from "next/font/google";
import "./globals.css";

// Components
import Navbar from "@/components/navigations/navbar";
import Footer from "@/components/navigations/footer";

export const metadata: Metadata = {
  title: "Pixel Joy",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`bg-background text-foreground relative ${poppins.className}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
